In [1]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import scale

In [2]:
df = pd.read_csv('wine.data')
df

1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29   5.64  1.04  \
0    1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
1    1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
2    1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
3    1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
4    1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.75  1.05   
..  ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
176  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

     3.92  1065  
0    3.40  1050  
1    3.17  1185  
2    3.45  1480  
3    2.93   735  
4    2.85  1450  
..    ...   ...  
172  1.74   740  
173  1.56   750  
174  1.56   835  
175  1.62   840  
176  1.60   560  

[177 rows x 14 columns]

In [3]:
df.columns = ['Class', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity', 'Magnesium', 'Total phenols', 'Flavanoids', 'Nonflavanoid', 'Proanthocyanins', 'Color', 'Hue', 'OD280/OD315', 'Proline']
df

Class  Alcohol  Malic acid   Ash  Alcalinity  Magnesium  Total phenols  \
0        1    13.20        1.78  2.14        11.2        100           2.65   
1        1    13.16        2.36  2.67        18.6        101           2.80   
2        1    14.37        1.95  2.50        16.8        113           3.85   
3        1    13.24        2.59  2.87        21.0        118           2.80   
4        1    14.20        1.76  2.45        15.2        112           3.27   
..     ...      ...         ...   ...         ...        ...            ...   
172      3    13.71        5.65  2.45        20.5         95           1.68   
173      3    13.40        3.91  2.48        23.0        102           1.80   
174      3    13.27        4.28  2.26        20.0        120           1.59   
175      3    13.17        2.59  2.37        20.0        120           1.65   
176      3    14.13        4.10  2.74        24.5         96           2.05   

     Flavanoids  Nonflavanoid  Proanthocyanins  Color   Hue  OD280/OD315  \
0          2.76          0.26             1.28   4.38  1.05         3.40   
1          3.24          0.30             2.81   5.68  1.03         3.17   
2          3.49          0.24             2.18   7.80  0.86         3.45   
3          2.69          0.39             1.82   4.32  1.04         2.93   
4          3.39          0.34             1.97   6.75  1.05         2.85   
..          ...           ...              ...    ...   ...          ...   
172        0.61          0.52             1.06   7.70  0.64         1.74   
173        0.75          0.43             1.41   7.30  0.70         1.56   
174        0.69          0.43             1.35  10.20  0.59         1.56   
175        0.68          0.53             1.46   9.30  0.60         1.62   
176        0.76          0.56             1.35   9.20  0.61         1.60   

     Proline  
0       1050  
1       1185  
2       1480  
3        735  
4       1450  
..       ...  
172      740  
173      750  
174      835  
175      840  
176      560  

[177 rows x 14 columns]

In [30]:
x = df.iloc[:, 1:14]
x

Alcohol  Malic acid   Ash  Alcalinity  Magnesium  Total phenols  \
0      13.20        1.78  2.14        11.2        100           2.65   
1      13.16        2.36  2.67        18.6        101           2.80   
2      14.37        1.95  2.50        16.8        113           3.85   
3      13.24        2.59  2.87        21.0        118           2.80   
4      14.20        1.76  2.45        15.2        112           3.27   
..       ...         ...   ...         ...        ...            ...   
172    13.71        5.65  2.45        20.5         95           1.68   
173    13.40        3.91  2.48        23.0        102           1.80   
174    13.27        4.28  2.26        20.0        120           1.59   
175    13.17        2.59  2.37        20.0        120           1.65   
176    14.13        4.10  2.74        24.5         96           2.05   

     Flavanoids  Nonflavanoid  Proanthocyanins  Color   Hue  OD280/OD315  \
0          2.76          0.26             1.28   4.38  1.05         3.40   
1          3.24          0.30             2.81   5.68  1.03         3.17   
2          3.49          0.24             2.18   7.80  0.86         3.45   
3          2.69          0.39             1.82   4.32  1.04         2.93   
4          3.39          0.34             1.97   6.75  1.05         2.85   
..          ...           ...              ...    ...   ...          ...   
172        0.61          0.52             1.06   7.70  0.64         1.74   
173        0.75          0.43             1.41   7.30  0.70         1.56   
174        0.69          0.43             1.35  10.20  0.59         1.56   
175        0.68          0.53             1.46   9.30  0.60         1.62   
176        0.76          0.56             1.35   9.20  0.61         1.60   

     Proline  
0       1050  
1       1185  
2       1480  
3        735  
4       1450  
..       ...  
172      740  
173      750  
174      835  
175      840  
176      560  

[177 rows x 13 columns]

In [54]:
x = scale(x)
x

array([[ 0.2558245 , -0.50162433, -0.8244853 , ...,  0.40709978,
         1.13169801,  0.97105248],
       [ 0.20622873,  0.01802001,  1.10768971, ...,  0.3195674 ,
         0.80457911,  1.40099798],
       [ 1.70650069, -0.34931478,  0.48793547, ..., -0.4244579 ,
         1.20281081,  2.34050852],
       ...,
       [ 0.34261709,  1.73822194, -0.38701171, ..., -1.60614514,
        -1.48525319,  0.28632445],
       [ 0.21862767,  0.22408586,  0.01400575, ..., -1.56237895,
        -1.39991783,  0.30224836],
       [ 1.40892609,  1.57695301,  1.36288264, ..., -1.51861275,
        -1.42836295, -0.58949046]])

In [31]:
y = df['Class']
y

0      1
1      1
2      1
3      1
4      1
      ..
172    3
173    3
174    3
175    3
176    3
Name: Class, Length: 177, dtype: int64

In [55]:
max = 0 
k = 0
for i in range(1, 50):
    clf = KNeighborsClassifier(n_neighbors=i)
    generator = KFold(n_splits=5, shuffle=True, random_state=42)
    error = cross_val_score(clf, x, y, scoring='accuracy', cv=generator)
    error = error.mean()
    if error > max:
        max = error
        k = i
print(k, max)

28 0.9773015873015873


In [73]:
from sklearn.datasets import load_boston
from numpy import linspace
from sklearn.neighbors import KNeighborsRegressor

In [74]:
data = load_boston()
data

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [75]:
x = data.data
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [76]:
x = scale(x)
x

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [77]:
y = data.target
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [78]:
space = linspace(1, 10 , num=200)
space

array([ 1.        ,  1.04522613,  1.09045226,  1.13567839,  1.18090452,
        1.22613065,  1.27135678,  1.31658291,  1.36180905,  1.40703518,
        1.45226131,  1.49748744,  1.54271357,  1.5879397 ,  1.63316583,
        1.67839196,  1.72361809,  1.76884422,  1.81407035,  1.85929648,
        1.90452261,  1.94974874,  1.99497487,  2.04020101,  2.08542714,
        2.13065327,  2.1758794 ,  2.22110553,  2.26633166,  2.31155779,
        2.35678392,  2.40201005,  2.44723618,  2.49246231,  2.53768844,
        2.58291457,  2.6281407 ,  2.67336683,  2.71859296,  2.7638191 ,
        2.80904523,  2.85427136,  2.89949749,  2.94472362,  2.98994975,
        3.03517588,  3.08040201,  3.12562814,  3.17085427,  3.2160804 ,
        3.26130653,  3.30653266,  3.35175879,  3.39698492,  3.44221106,
        3.48743719,  3.53266332,  3.57788945,  3.62311558,  3.66834171,
        3.71356784,  3.75879397,  3.8040201 ,  3.84924623,  3.89447236,
        3.93969849,  3.98492462,  4.03015075,  4.07537688,  4.12

In [83]:
clf = KNeighborsRegressor(weights='distance', p=2)
generator = KFold(n_splits=5, shuffle=True, random_state=42)
error = cross_val_score(clf, x, y, scoring='neg_mean_squared_error', cv=generator)
error = error.mean()
print(error)

-17.333314407343945
