In [10]:
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score

In [3]:
df = pd.read_csv('data.csv', header=None)
df

0         1          2
0   -1 -0.663827  -0.138526
1    1  1.994596   2.468025
2   -1 -1.247395   0.749425
3    1  2.309374   1.899836
4    1  0.849143   2.407750
..  ..       ...        ...
200  1  4.245176   3.053931
201  1  2.437935   1.357804
202 -1 -1.876638   1.533398
203  1 -6.824446 -13.934211
204 -1  0.001805   0.865147

[205 rows x 3 columns]

In [4]:
x = df.iloc[:,1:3]
x

1          2
0   -0.663827  -0.138526
1    1.994596   2.468025
2   -1.247395   0.749425
3    2.309374   1.899836
4    0.849143   2.407750
..        ...        ...
200  4.245176   3.053931
201  2.437935   1.357804
202 -1.876638   1.533398
203 -6.824446 -13.934211
204  0.001805   0.865147

[205 rows x 2 columns]

In [31]:
x = np.array(x)
x.shape

(205, 2)

In [28]:
y = np.array(df.iloc[:,0])
y

array([-1,  1, -1,  1,  1,  1,  1, -1, -1,  1, -1, -1, -1, -1,  1, -1, -1,
        1,  1,  1, -1,  1, -1, -1, -1, -1,  1,  1, -1, -1, -1, -1,  1,  1,
       -1, -1,  1,  1, -1,  1,  1, -1,  1, -1, -1,  1,  1, -1, -1,  1,  1,
        1, -1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1, -1,  1, -1,  1,
       -1,  1,  1, -1,  1, -1, -1, -1,  1, -1,  1, -1,  1, -1,  1,  1, -1,
        1,  1, -1,  1, -1, -1, -1,  1, -1, -1,  1,  1, -1, -1, -1,  1,  1,
       -1, -1, -1,  1,  1,  1,  1, -1, -1,  1,  1,  1, -1,  1, -1, -1,  1,
       -1,  1, -1,  1, -1,  1,  1,  1, -1,  1,  1,  1, -1, -1, -1,  1, -1,
        1, -1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1,
       -1,  1, -1, -1,  1, -1, -1, -1, -1,  1,  1,  1,  1, -1,  1, -1, -1,
        1, -1, -1, -1,  1,  1, -1,  1, -1,  1,  1, -1,  1, -1,  1, -1, -1,
       -1, -1, -1,  1,  1, -1, -1,  1,  1, -1,  1,  1, -1,  1,  1, -1,  1,
       -1], dtype=int64)

In [8]:
w = np.array([0,0])
w

array([0, 0])

In [36]:
import math

def grad(X, y, w, C=0, k = 0.1, max_step = 10000):
    eps = 1e-5
    s1 = 0
    s2 = 0
    l = X.shape[0]
    for _ in range(max_step):
        w0 = w
        for i in range(l):
            s1 += y[i] * X[i][0] * (1 - (1 + math.exp(-y[i]*(w[0]*X[i][0] + w[1]*X[i][1])))**(-1))
            s2 += y[i] * X[i][1] * (1 - (1 + math.exp(-y[i]*(w[0]*X[i][0] + w[1]*X[i][1])))**(-1))
        w[0] = w[0] + k / l * s1 - k * C * w[0]
        w[1] = w[1] + k / l * s2 - k * C * w[1]
        if math.sqrt((w0[0] - w[0])**2 + (w0[1] - w[1])**2) < eps:
            break
    return w

def sigmoda(X, w):
    return 1 / (1 + np.exp(-w[0] * X[:, 0] - w[1] * X[:, 1]))

In [37]:
grad(x, y, w)

array([0, 0])