In [27]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from numpy import corrcoef

In [28]:
prices = pd.read_csv('close_prices.csv')
indexes = pd.read_csv('dj_index.csv')
prices

date        AXP          BA        CAT       CSCO         CVX  \
0    2013-09-23  76.440002  117.510002  85.029999  24.270000  125.519997   
1    2013-09-24  76.070000  119.000000  85.110001  24.139999  124.489998   
2    2013-09-25  75.989998  118.510002  84.500000  24.430000  124.070000   
3    2013-09-26  76.320000  119.379997  84.199997  23.770000  123.489998   
4    2013-09-27  75.889999  118.739998  83.800003  23.330000  122.639999   
..          ...        ...         ...        ...        ...         ...   
369  2015-03-12  81.559998  152.039993  80.190002  28.240000  102.419998   
370  2015-03-13  80.599998  151.570007  79.230003  27.940001  101.620003   
371  2015-03-16  81.500000  153.669998  79.970001  28.299999  103.129997   
372  2015-03-17  81.059998  154.509995  78.449997  28.150000  103.169998   
373  2015-03-18  81.860001  155.729996  81.330002  28.150000  106.699997   

            DD         DIS         GE          GS  ...        PFE         PG  \
0    59.409999   64.750000  24.280001  165.250000  ...  28.799999  79.279999   
1    59.319997   64.320000  24.320000  162.970001  ...  28.709999  78.620003   
2    59.319997   64.449997  24.230000  162.309998  ...  28.490000  77.720001   
3    59.509996   65.239998  24.250000  162.289993  ...  28.520000  78.050003   
4    59.009995   65.190002  24.049999  159.850006  ...  28.879999  77.209999   
..         ...         ...        ...         ...  ...        ...        ...   
369  80.400001  107.169998  25.400000  189.949997  ...  34.000000  82.089996   
370  80.499997  106.440002  25.040001  189.339996  ...  34.000000  81.830002   
371  77.069994  107.370003  25.450001  191.899994  ...  34.439999  83.559998   
372  74.680001  106.959999  25.309999  190.570007  ...  34.169998  82.849998   
373  76.009997  107.970001  25.639999  192.320007  ...  34.380001  83.750000   

             T         TRV         UNH         UTX           V         VZ  \
0    34.220001   86.379997   71.820000  109.419998  196.240005  47.980000   
1    34.090000   85.870003   72.320000  110.000000  193.339996  47.270000   
2    34.049999   85.980003   71.980003  109.260002  191.559998  46.950001   
3    34.230000   85.830002   72.160004  109.660004  193.559998  47.669998   
4    33.980000   85.410004   71.989998  109.360001  193.050003  47.000000   
..         ...         ...         ...         ...         ...        ...   
369  33.130001  107.830002  114.879997  121.239998  269.579987  48.730000   
370  32.759998  106.720001  115.250000  118.739998  265.029999  48.840000   
371  33.060001  108.930000  118.519997  120.070000  269.019989  49.270000   
372  32.900002  108.750000  117.599998  119.860001  264.500000  48.950001   
373  33.590000  109.519997  119.959999  120.309998  267.670013  49.540001   

           WMT        XOM  
0    76.419998  87.750000  
1    75.750000  87.360001  
2    74.650002  87.139999  
3    74.620003  87.070000  
4    74.360001  86.900002  
..         ...        ...  
369  81.900002  84.220001  
370  81.900002  83.870003  
371  83.290001  84.760002  
372  82.620003  84.080002  
373  82.529999  86.070000  

[374 rows x 31 columns]

In [29]:
indexes

date          ^DJI
0    2013-09-23  15401.379883
1    2013-09-24  15334.589844
2    2013-09-25  15273.259766
3    2013-09-26  15328.299805
4    2013-09-27  15258.240234
..          ...           ...
369  2015-03-12  17895.220703
370  2015-03-13  17749.310547
371  2015-03-16  17977.419922
372  2015-03-17  17849.080078
373  2015-03-18  18076.189453

[374 rows x 2 columns]

In [30]:
x = np.array(prices.iloc[:, 1:32])
x

array([[ 76.440002, 117.510002,  85.029999, ...,  47.98    ,  76.419998,
         87.75    ],
       [ 76.07    , 119.      ,  85.110001, ...,  47.27    ,  75.75    ,
         87.360001],
       [ 75.989998, 118.510002,  84.5     , ...,  46.950001,  74.650002,
         87.139999],
       ...,
       [ 81.5     , 153.669998,  79.970001, ...,  49.27    ,  83.290001,
         84.760002],
       [ 81.059998, 154.509995,  78.449997, ...,  48.950001,  82.620003,
         84.080002],
       [ 81.860001, 155.729996,  81.330002, ...,  49.540001,  82.529999,
         86.07    ]])

In [31]:
pca = PCA(n_components=10)
pca.fit(x)
pca.explained_variance_ratio_

array([0.73897118, 0.11007169, 0.04995088, 0.0287492 , 0.02215448,
       0.01931577, 0.00674853, 0.00614091, 0.00320594, 0.00305611])

In [32]:
count = 0
sum = 0
for i in range(len(pca.explained_variance_ratio_)):
    count+=1
    value = pca.explained_variance_ratio_[i]
    sum+= value
    if sum > 0.9:
        break
print("Need components %d" % count)

Need components 4


In [33]:
component = pd.DataFrame(pca.transform(x)[:,0])
component

0
0   -50.902404
1   -52.846909
2   -54.614439
3   -52.600566
4   -52.370123
..         ...
369  81.290980
370  77.903534
371  83.798199
372  79.195789
373  82.968859

[374 rows x 1 columns]

In [34]:
index = indexes['^DJI']
index

0      15401.379883
1      15334.589844
2      15273.259766
3      15328.299805
4      15258.240234
           ...     
369    17895.220703
370    17749.310547
371    17977.419922
372    17849.080078
373    18076.189453
Name: ^DJI, Length: 374, dtype: float64

In [41]:
corrcoef(component.T, index.T)[1,0]

0.9096522193050238

In [47]:
pca.components_[0]

array([ 1.61383840e-02,  1.20644923e-01, -5.16612711e-02,  5.04842369e-02,
       -1.25859933e-01,  1.14089567e-01,  2.33906290e-01, -6.20513749e-03,
        2.51227032e-01,  2.88996029e-01, -2.64998795e-01,  9.31320168e-02,
        9.13948403e-02,  4.69879340e-02,  2.90549417e-02, -2.61068828e-02,
        3.29615584e-01,  7.13897133e-02,  7.62295699e-02,  2.11888868e-01,
        2.30922941e-02,  7.77316954e-02, -7.20594590e-03,  1.89479745e-01,
        3.21564017e-01,  5.36834873e-02,  5.79683946e-01,  1.09122230e-04,
        8.71614334e-02, -4.29421420e-02])

In [52]:
val = -1
ind = 0
for i in range(len(pca.components_[0])):
    if pca.components_[0][i] > val:
        val = pca.components_[0][i]
        ind = i
prices.columns[ind + 1]

'V'

In [48]:
prices.columns[26]

'UTX'